webapp/message/models.py
import datetime
from webapp.db import db


class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    sender_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    recipient_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True,
                          default=datetime.datetime.utcnow)

    def __repr__(self):
        return f'<Message {self.body}>'

webapp/message/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class MessageForm(FlaskForm):
    message = TextAreaField('Message',
                            validators=[DataRequired(),
                                        Length(min=0, max=140)],
                            render_kw={"class": "form-control",
                                       "placeholder": "Enter your message"})
    submit = SubmitField('Submit', render_kw={"class": "btn btn-success"})

webapp/message/views.py
import datetime
from webapp.message.forms import MessageForm
from webapp.message.models import Message

from flask import Blueprint, render_template, redirect, url_for, \
    request, current_app, flash, jsonify
from flask_login import current_user, login_required

from webapp.market.models import Auto, Params, Images, Auto_brand,\
    Auto_models
from webapp.user.forms import RegistrationForm, LogoutForm
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('message', __name__)


@blueprint.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(id=recipient).first_or_404()
    msgform = MessageForm()
    if msgform.validate_on_submit():
        new_msg = Message(
            sender_id=current_user.id,
            recipient_id=user.id,
            body=msgform.message.data)
        print(new_msg)
        db.session.add(new_msg)
        db.session.commit()
        flash('Ваше сообщение отправлено!')
        return redirect(url_for('market.index'))
    flash('Сообщение не отправлено')
    return redirect(url_for('market.index'))


@blueprint.route('/messages')
@login_required
def messages():
    form = RegistrationForm()
    logoutform = LogoutForm()
    current_user.last_message_read_time = datetime.datetime.utcnow()
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    received_msg = Message.query.filter(
        Message.recipient_id == current_user.id).order_by(
        Message.timestamp.desc()).paginate(
            page, current_app.config['MESSAGES_PER_PAGE'], False)
    
    next_url = url_for('message.messages', page=received_msg.next_num) \
        if received_msg.has_next else None
    prev_url = url_for('message.messages', page=received_msg.prev_num) \
        if received_msg.has_prev else None
    return render_template('message/messages.html',
                           received_msg=received_msg.items,
                           next_url=next_url, prev_url=prev_url, form=form,
                           logoutform=logoutform)



@blueprint.route('/sent_messages')
@login_required
def sent_messages():
    form = RegistrationForm()
    logoutform = LogoutForm()
    current_user.last_message_read_time = datetime.datetime.utcnow()
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    sent_msg = Message.query.filter(
        Message.sender_id == current_user.id).order_by(
        Message.timestamp.desc()).paginate(
            page, current_app.config['MESSAGES_PER_PAGE'], False)
    
    next_url = url_for('message.sent_messages', page=sent_msg.next_num) \
        if sent_msg.has_next else None
    prev_url = url_for('message.sent_messages', page=sent_msg.prev_num) \
        if sent_msg.has_prev else None
    return render_template('message/sent_messages.html',
                           next_url=next_url, prev_url=prev_url, form=form,
                           logoutform=logoutform, sent_msg=sent_msg.items)

webapp/user/views.py
import logging

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user, login_required

from webapp.user.forms import RegistrationForm, LoginForm, LogoutForm
from webapp.message.forms import MessageForm
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/id_<id>')
@login_required
def user_account(id):
    title = 'Профиль'
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    msgform = MessageForm()
    user = User.query.filter_by(id=id).first()
    return render_template('user/account.html', user=user, page_title=title,
                           form=form, regform=regform,
                           logoutform=logoutform, msgform=msgform)


@blueprint.route('/login', methods=['POST'])
def process_login():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(mail=form.mail.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'Вы вошли! Привет {user.name}!')
            logging.info(f'Зашел пользователь с id={user.id}')
            return redirect(url_for('market.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('market.index'))


@blueprint.route('/process_registration', methods=['POST'])
def process_registration():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    regform = RegistrationForm()
    if regform.validate_on_submit():
        new_user = User(number=f'8{regform.number.data}',
                        mail=regform.mail.data,
                        name=regform.name.data,
                        role='user'
                        )
        new_user.set_password(regform.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash('Вы успешно зарегистрировались!')
        logging.info(f'Новый пользователь с id={new_user.id}')
        return redirect(url_for('market.index'))
    else:
        for field, errors in regform.errors.items():
            for error in errors:
                flash(
                 f"В поле {getattr(regform, field).label.text}: -{error}")
        return redirect(url_for('market.registration'))


@blueprint.route('/logout', methods=['POST'])
def logout():
    logging.info(f'Вышел пользователь с id={current_user.id}')
    logout_user()
    flash('Вы вышли из аккаунта!')
    return redirect(url_for('market.index'))

webapp/templates/message/messages.html
{% extends "base.html" %}

{% block account %}
<div class="col-2 border-right" style="padding-top:10px">
    <ul class="nav nav-pills">
        <li class="nav-item ">
            <a class="nav-link " href="/">На главную</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{{ url_for('user.user_account', id=current_user.id) }}">Аккаунт</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active " style="background-color:rgb(128, 69, 170)" href="{{ url_for('message.messages') }}">Сообщения</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">Настройки</a>
        </li>
    </ul>
</div>
<div class="col-10">
    <div class="row"><h1>Сообщения</h1></div>
    <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link active" style="background-color:#20c997" href="{{ url_for('message.messages') }}">Полученные</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  href="{{ url_for('message.sent_messages') }}">Отправленные</a>
            </li>
    </ul>
    <div class="row">
        <div class="col" style=" padding-top: 20px">
            {% if received_msg == [] %}
            <div class="container" style="padding-bottom:20px">
                <i> Вы не получили еще ни одного сообщения </i>
            </div>
            
            {% else %}
                {% for message in received_msg %}
                <div class="container border border-info" >
                    <p>
                        <a href="{{ url_for('user.user_account', id=message.author.id) }}">
                            {{ message.author.uname }} 
                        </a>
                        написал(а): <b>{{ message.body }}</b> <br>в: {{ message.timestamp }}
                    </p>
                    <button class="btn btn-light">
                        <a href="{{ url_for('message.send_message', recipient=message.author.id ) }}">Ответить</a>
                    </button>
                </div>
                {% endfor %}
                <div class="row" style="padding-bottom: 20px; padding-top: 20px; margin-left: 30%">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item next{% if not next_url %} disabled{% endif %}">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            {% endif %}
        </div>
</div>

{% endblock %}

webapp/templates/message/modal.html
<div class="modal fade" id="MessageModal" tabindex="-1" role="dialog" aria-labelledby="MessageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="MessageModalLabel">New message</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="{{ url_for('message.send_message', recipient=user.id) }}" method="POST">
                {{ msgform.hidden_tag() }}
                <div class="form-group">
                    Получатель: {{ user.username }}
                </div>
                <div class="form-group">
                    {{ msgform.message.label }}
                    {{ msgform.message() }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    {{ msgform.submit() }}
                </div>
            </form>
        </div>
        </div>
    </div>
</div>

webapp/templates/message/sent_messages.html
{% extends "base.html" %}

{% block account %}
<div class="col-2 border-right" style="padding-top:10px">
    <ul class="nav nav-pills">
        <li class="nav-item ">
            <a class="nav-link " href="/">На главную</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link " href="{{ url_for('user.user_account', id=current_user.id) }}">Аккаунт</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link active" style="background-color:rgb(128, 69, 170)" href="{{ url_for('message.messages') }}">Сообщения</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="#">Настройки</a>
        </li>
    </ul>
</div>
<div class="col-10">
    <div class="row"><h1>Сообщения</h1></div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link "  href="{{ url_for('message.messages') }}">Полученные</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" style="background-color:#20c997" href="{{ url_for('message.sent_messages') }}">Отправленные</a>
        </li>
    </ul>
    <div class="col" style=" padding-top: 20px">
        {% if sent_msg == [] %}
        <div class="container" style="padding-bottom:20px">
            <i> Вы не написали еще ни одного сообщения </i>
        </div>
        {% else %}
            {% for message in sent_msg %}
                <div class="container border border-info">
                    <p>
                        Получатель: 
                        <a href="{{ url_for('user.user_account', id=message.recipient.id) }}">
                        {{ message.recipient.name }}
                        </a>
                        <br> Сообщение: <b>{{ message.body }}</b> <br>в: {{ message.timestamp }}
                    </p>
                </div>
            {% endfor %}
            <div class="row" style="padding-bottom: 20px; padding-top: 20px; margin-left: 30%">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item next{% if not next_url %} disabled{% endif %}">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                        </li>
                    </ul>
                </nav>
            </div>
        {% endif %}
        </div>
    </div>
</div>

{% endblock %}