webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, \
                               ValidationError

from webapp.user.models import User


class RegistrationForm(FlaskForm):
    name = StringField('Имя', validators=[DataRequired()],
                           render_kw={"class": "form-control",
                                      "placeholder": "Введите Ваше имя"})
    number = StringField('Номер телефона', validators=[
        DataRequired(),
        Length(
            min=10,
            max=10,
            message="Номер очень короткий, введите 10 цифр")],
                             render_kw={"class": "form-control",
                                        "maxlength": 10,
                                        "placeholder": "1234567890",
                                        })
    mail = StringField('Почта', validators=[
        DataRequired(),
        Email(
            message="Введите правильный электронный адрес"
        )],
                            render_kw={"class": "form-control",
                                       "placeholder": "example@mail.ru"})
    password = PasswordField('Пароль', validators=[
        DataRequired(),
        Length(
            min=8,
            max=32,
            message="Пароль должен быть минимум 8 символов")],
                             render_kw={"class": "form-control"})
    password2 = PasswordField(
        'Повторите пароль', 
        validators=[
            DataRequired(),
            Length(min=8,
                   max=32,
                   message="Пароль должен быть минимум 8 символов"),
            EqualTo(
                'password',
                message="Пароли не совпадают")],
        render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True,
                               render_kw={"class": "form-check-input"})
    submit = SubmitField('Зарегестрироваться',
                         render_kw={"class": "btn btn-success"})

    def validate_email(self, user_mail):
        form = RegistrationForm()
        user_count = User.query.filter_by(
            user_mail=form.user_mail.data).count()
        if user_count > 0:
            raise ValidationError('Такая почта уже зарегистрирована')

    def validate_tel(self, tel_number):
        form = RegistrationForm()
        if len(form.tel_number.data) == 10:
            user_count = User.query.filter_by(
                tel_number=form.tel_number.data).count()
            if user_count > 0:
                raise ValidationError('Этот номер уже зарегистрирован')
        raise ValidationError('Введите правильный номер')


class LoginForm(FlaskForm):
    mail = StringField('Почта', validators=[
        DataRequired(),
        Email(
            message="Введите правильный электронный адрес"
        )],
                            render_kw={"class": "form-control",
                                       "placeholder": "example@mail.ru"})
    password = PasswordField('Пароль', validators=[
        DataRequired(),
        Length(
            min=8,
            max=32,
            message="Пароль должен быть минимум 8 символов")],
                             render_kw={"class": "form-control"})
    submit = SubmitField('Войти',
                         render_kw={"class": "btn btn-success"})
    remember_me = BooleanField('Запомнить меня', default=True,
                               render_kw={"class": "form-check-input"})


class LogoutForm(FlaskForm):
    choice_yes = SubmitField('Выйти',  render_kw={"class": "btn btn-danger"})

webapp/images/views.py
from flask import Blueprint, send_from_directory, current_app


blueprint = Blueprint('img', __name__)

# Какой URL он подкладывает. hekp
@blueprint.route('/hekp/<path:filename>')
def send_file(filename):
    return send_from_directory(f'{current_app.static_folder}/static', filename)
# Куда он смотрит на самом деле
@blueprint.route('/hekp/uploaded/<path:filename>')
def send_picture(filename):
    return send_from_directory(
        f'{current_app.static_folder}/uploaded', filename)

@blueprint.route('/hekp/numbers/<path:filename>')
def send_number(filename):
    return send_from_directory(
        f'{current_app.static_folder}/numbers', filename)

webapp/market/views.py
import os

from flask import Blueprint, render_template, redirect, url_for, \
    request, current_app, flash, jsonify
from flask_login import current_user, login_required

from webapp.market.models import Auto, Params, Images, Auto_brand,\
    Auto_models
from webapp.user.forms import RegistrationForm, LogoutForm,\
    LoginForm
from webapp.market.forms import AddForm, DeleteForm, EditForm, FilterForm
from webapp.message.forms import MessageForm
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('market', __name__)


@blueprint.route('/')
def index():
    page_title = 'Не бита, не крашена!'
    fform = FilterForm()
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.order_by(Auto_brand.id).all()
    count = {}
    for br in brands:
        auto = Auto.query.filter_by(brand_id=br.id).all()
        count[br.name] = len(auto)
    page = request.args.get('page', 1, type=int)
    full_auto_list = Auto.query.order_by(Auto.id).all()
    auto_list = Auto.query.order_by(Auto.id).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    return render_template('market/index.html', page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, full_auto_list=full_auto_list,
                           count=count, fform=fform
                           )


@blueprint.route('/brand_<brand>')
def filter_brand(brand):
    page_title = 'Не бита, не крашена!'
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.filter_by(id=brand).all()
    page = request.args.get('page', 1, type=int)
    auto_list = Auto.query.filter_by(brand_id=brand).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    models = Auto_models.query.filter_by(brand_id=brand).all()
    count = {}
    for model in models:
        auto = Auto.query.filter_by(model_id=model.id).all()
        count[model.name] = len(auto)
    return render_template('market/filter_by_brand.html',
                           page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, models=models, count=count
                           )

@blueprint.route('/brand_<brand>/<model>')
def filter_model(brand, model):
    page_title = 'Не бита, не крашена!'
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.filter_by(id=brand).all()
    page = request.args.get('page', 1, type=int)
    auto_list = Auto.query.filter_by(model_id=model).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    models = Auto_models.query.filter_by(brand_id=brand).all()
    count = {}
    for model in models:
        auto = Auto.query.filter_by(model_id=model.id).all()
        count[model.name] = len(auto)
    return render_template('market/filter_by_brand.html',
                           page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, models=models, count=count
                           )


@blueprint.route('/registration')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    page_title = 'Регистрация на сайте - Не бита, не крашена!'
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()

    return render_template('user/registration.html', page_title=page_title,
                           form=form, regform=regform,
                           logoutform=logoutform)


@blueprint.route('/auto/add_auto')
@login_required
def add_auto():
    page_title = 'Разместить объявление на сайте - Не бита, не крашена!'
    form = LoginForm()
    regform = RegistrationForm()
    addform = AddForm()
    logoutform = LogoutForm()
    addform.brand.choices = [(
        brand.id, brand.name) for brand in Auto_brand.query.all()]

    addform.model.choices = [(
        model.id, model.name) for model in Auto_models.query.filter_by(
            brand_id=addform.brand.choices[0][0]).all()]

    return render_template('market/add.html', page_title=page_title,
                           form=form, regform=regform,
                           logoutform=logoutform, addform=addform)


@blueprint.route('/delete/auto_<id>', methods=['POST'])
def del_auto(id):
    auto = Auto.query.filter_by(id=id).first()
    auto.active = False
    db.session.commit()

    flash(f"Объявление {auto.name} успешно удалено!")
    return redirect(url_for('user.user_account', id=current_user.id))


@blueprint.route('/sell_auto/edit/<id>', methods=["GET", "POST"])
def edit_auto(id):
    page_title = 'Редактирование объявления'
    editform = EditForm()
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    auto = Auto.query.filter_by(id=id).first()
    if editform.validate_on_submit():
        auto.price = editform.price.data
        auto.description = editform.description.data
        auto.mileage = editform.mileage.data
        uploaded_files = request.files.getlist('url_picture')
        for file in uploaded_files:
            file.save(os.path.join(
                f'{current_app.static_folder}/uploaded', file.filename))
            new_auto_i = Images(
                auto_id=auto.id,
                url_picture=file.filename)
            db.session.add(new_auto_i)
        db.session.commit()
        flash(f"Объявление {auto.name} успешно отредактировано!")
        return redirect(url_for('market.auto_account', id=id))
    return render_template('market/edit.html', page_title=page_title,
                           logoutform=logoutform, editform=editform,
                           form=form, regform=regform, auto=auto)


@blueprint.route('/auto/<id>')
def brand(id):
    brands = Auto_brand.query.filter_by(id=id).all()
    brandArr = []
    modelArr = []
    for brand in brands:
        brandObj = {}
        brandObj['id'] = id
        brandObj['name'] = brand.name
        models = Auto_models.query.filter_by(brand_id=id).all()
        for model in models:
            modelObj = {}
            modelObj['id'] = model.id
            modelObj['name'] = model.name
            modelArr.append(modelObj)
            brandObj['models'] = modelArr
            brandArr.append(brandObj)
    return jsonify(brandObj)


@blueprint.route('/process_add', methods=['POST'])
@login_required
def process_add():
    addform = AddForm()
    brand = Auto_brand.query.filter_by(id=addform.brand.data).first()
    model = Auto_models.query.filter_by(id=addform.model.data).first()
    new_auto = Auto(
        price=addform.price.data,
        description=addform.description.data,
        name=f'{brand.name} {model.name}, {addform.year.data}',
        user_id=current_user.id,
        brand_id=brand.id,
        model_id=model.id
        )

    db.session.add(new_auto)
    db.session.commit()
    new_auto_p = Params(
        auto_id=new_auto.id,
        holders=addform.holders.data,
        condition=addform.condition.data,
        steering_wheel=addform.steering_wheel.data,
        wheeldrive=addform.wheeldrive.data,
        color=addform.color.data,
        model=model.name,
        mileage=addform.mileage.data,
        brand=brand.name,
        year=addform.year.data,
        body_type=addform.body_type.data,
        type_engine=addform.type_engine.data,
        gear=addform.gear.data)

    uploaded_files = request.files.getlist('url_picture')
    for file in uploaded_files:
        file.save(os.path.join(
            f'{current_app.static_folder}/uploaded', file.filename))
        new_auto_i = Images(
            auto_id=new_auto.id,
            url_picture=file.filename
        )
        db.session.add(new_auto_i)
    db.session.commit()
    db.session.add(new_auto_p)
    db.session.commit()
    flash(f"Объявление {new_auto.name} успешно размещено!")
    return redirect(url_for('market.index'))


@blueprint.route('/sell_auto/<id>')
def auto_account(id):
    auto = Auto.query.filter_by(id=id).first()
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    delform = DeleteForm()
    msgform = MessageForm()
    if auto.active is True:
        params = Params.query.join(Auto).filter_by(id=id).first()
        all_params = {
            'Владельцев по ПТС': params.holders,
            'Поколение': params.generation,
            'Состояние': params.condition, 'Руль': params.steering_wheel,
            'Привод': params.wheeldrive,
            'Цвет': params.color, 'Объём двигателя': params.engine_capacity,
            'Модель': params.model,
            'Пробег': params.mileage, 'Марка': params.brand,
            'Год выпуска': params.year,
            'Тип кузова': params.body_type,
            'Тип двигателя': params.type_engine,

webapp/user/views.py
import logging

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user, login_required

from webapp.user.forms import RegistrationForm, LoginForm, LogoutForm
from webapp.message.forms import MessageForm
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/id_<id>')
@login_required
def user_account(id):
    title = 'Профиль'
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    msgform = MessageForm()
    user = User.query.filter_by(id=id).first()
    return render_template('user/account.html', user=user, page_title=title,
                           form=form, regform=regform,
                           logoutform=logoutform, msgform=msgform)


@blueprint.route('/login', methods=['POST'])
def process_login():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(mail=form.mail.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'Вы вошли! Привет {user.name}!')
            logging.info(f'Зашел пользователь с id={user.id}')
            return redirect(url_for('market.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('market.index'))


@blueprint.route('/process_registration', methods=['POST'])
def process_registration():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    regform = RegistrationForm()
    if regform.validate_on_submit():
        new_user = User(number=f'8{regform.number.data}',
                        mail=regform.mail.data,
                        name=regform.name.data,
                        role='user'
                        )
        new_user.set_password(regform.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash('Вы успешно зарегистрировались!')
        logging.info(f'Новый пользователь с id={new_user.id}')
        return redirect(url_for('market.index'))
    else:
        for field, errors in regform.errors.items():
            for error in errors:
                flash(
                 f"В поле {getattr(regform, field).label.text}: -{error}")
        return redirect(url_for('market.registration'))


@blueprint.route('/logout', methods=['POST'])
def logout():
    logging.info(f'Вышел пользователь с id={current_user.id}')
    logout_user()
    flash('Вы вышли из аккаунта!')
    return redirect(url_for('market.index'))

webapp/templates/user/account.html
{% extends 'base.html' %}

{% block account %}
<div class="col-2 border-right" style="padding-top:10px">
        <ul class="nav nav-pills">
            <li class="nav-item ">
                <a class="nav-link "  href="/">На главную</a>
            </li>
        {% if current_user.id == user.id %}
        <li class="nav-item" >
            <a class="nav-link active " style="background-color:rgb(128, 69, 170)" href="{{ url_for('user.user_account', id=current_user.id) }}">Аккаунт</a>
        </li>
        {% else %}
        <li class="nav-item ">
            <a class="nav-link disabled " style="background-color:rgb(128, 69, 170)" href="{{ url_for('user.user_account', id=current_user.id) }}"> Аккаунт</a>
        </li>
        {% endif %}
        <li class="nav-item ">
            <a class="nav-link " href="{{ url_for('message.messages') }}">Сообщения</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">Настройки</a>
        </li>
    </ul>
</div>

<div class="col-10">
    <div class="row">
        <div class="col-3">PROFILE PHOTO<br>{{ user.avatar }}</div>
        <div class="col-9">
            ABOUT OF USER AND SETTINGS?!<br>
            <div class="row">
                <div class="box">
                   <b>{{ user.name }}</b>
                   <p>{{ user.street_address }}</p>  
                </div>
                
            </div>
            <div class="row">
                {% if current_user.id == user.id %}
                    <div class="col-9">
                        {% if user.auto == [] %}
                            <i>Нет размещенных объявлений</i>
                        {% else %}
                            {% for aut in user.auto %}
                            <a href="{{ url_for('market.auto_account', id=aut.id) }}">
                            <div class="media">
                                <img src='{{ url_for("img.send_picture", filename=aut.images[0].url_picture) }}' class="rounded-sm" alt="..." style="height: 50px;"/>
                                <div class="media-body">
                                <h5 class="mt-0">{{ aut.name }}</h5>
                                    {{ aut.price }}
                                </div>
                            </div> 
                            </a>
                            {% endfor%}
                        {% endif %}
                </div>
                <div class="col-3">
                    <a class="text-dark" href="{{ url_for('market.add_auto') }}">Разместить объявление</a>
                </div>
            </div>
                {% else %}
                <div class="col-9">
                    {% if user.auto == None %}
                       <i>Нет размещенных объявлений</i>
                   {% else %}
                       <i>Объявления пользователя:</i>
                        {% for aut in user.auto %}
                        <a href="{{ url_for('market.auto_account', id=aut.id) }}">
                        <div class="media">
                            <img src='{{ url_for("img.send_picture", filename=aut.images[0].url_picture) }}' class="rounded-sm" alt="..." style="height: 50px;"/>
                            <div class="media-body">
                            <h5 class="mt-0">{{ aut.name }}</h5>
                                {{ aut.price }}
                            </div>
                        </div> 
                        </a>
                        {% endfor%}
                    {% endif %}
                </div>
                <div class="col-3">
                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#MessageModal">
                        Написать сообщение        
                    </button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
</div>
{% include 'message/modal.html' %}
{% endblock account %}

webapp/templates/user/modal.html
{% if not current_user.is_authenticated %}
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="LoginModal">Авторизация</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action='{{  url_for("user.process_login") }}' method='POST'>
                <div class="modal-body">
                {{ form.hidden_tag() }}
                    <div class="form-group">
                    {{ form.mail.label }}
                    {{ form.mail() }}
                    </div>
                    <div class="form-group">          
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group form-check">
                        {{ form.remember_me() }}
                        {{ form.remember_me.label(class_='form-check-label') }}
                    </div>
                    <div class="form-group">
                        {{ form.submit() }}
                    </div>
                    
                </div>
            </form>
        </div>
    </div>
</div>
{% else %}
<div class="modal fade" id="LogoutModal" tabindex="-1" role="form" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="LogoutModal">Выход</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action='{{  url_for("user.logout") }}' method='POST'>
        <div class="modal-body">
          Вы действительно хотите выйти?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Остаться</button>
          {{ logoutform.choice_yes() }}
        </div>
      </form>
    </div>
  </div>
</div>

{% endif %}

webapp/templates/user/registration.html
{% extends 'base.html' %}

{% block content %}
<div class="col-6">
  <form action='{{  url_for("user.process_registration")  }}' method='POST'>
    <div class="modal-body">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ regform.number.label }}
        {{ regform.number(size=10) }}
        <small id="telefone_numHelpBlock" class="form-text text-muted">
          Номер должен состоять из 10 цифр, вводить без 8.
        </small>
      </div>
      <div class="form-group">
        {{ regform.mail.label }}
        {{ regform.mail() }}
        
      </div>
      <div class="form-group">
        {{ regform.name.label }}
        {{ regform.name() }}
        
      </div>
      <div class="form-group">          
        {{ regform.password.label }}
        {{ regform.password() }}
        <small id="passwordHelpBlock" class="form-text text-muted">
          Ваш пароль должен состоять из 8-32 букв и цифр, не должно быть пробелов, специальных символов и смайлов.
        </small>
      </div>
      <div class="form-group">         
        {{ regform.password2.label }}
        {{ regform.password2() }}
        
      </div>
    </div>
    <div class="modal-footer">
      <div class="form-group">
        {{ regform.submit() }}
      </div>
    </div>
  </form>
</div>
<script>
  let tel_select = document.getElementById('number');
  let mail_select = document.getElementById('mail');

  tel_select.onkeypress= function(event) {
    event = event || window.event;
    if (event.charCode && (event.charCode <12 || event.charCode > 57))
    return false;
  }
  
</script>
{% endblock content %}