webapp/market/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField

from wtforms import StringField, SubmitField, IntegerField, SelectField,\
    TextAreaField
from wtforms.validators import DataRequired, InputRequired


class AddForm(FlaskForm):
    price = IntegerField('Цена', validators=[DataRequired()],
                         render_kw={"class": "form-control form-control-sm",
                                    "placeholder": "100000"})

    description = TextAreaField('Описание', validators=[DataRequired()],
                                render_kw={
                                    "class": "form-control form-control-sm",
                                    "rows": "3",
                                    "placeholder": "Опишите "})
    holders = SelectField('Владельцев по ПТС', validators=[DataRequired()],
                          render_kw={"class": "form-control form-control-sm"},
                          choices=[
                              ('1', '1'), ('2', '2'),
                              ('3', '3'), ('4+', '4+')])

    condition = SelectField('Состояние', validators=[DataRequired()],
                            render_kw={"class": "form-control form-control-sm"},
                            choices=[('не битая', 'Не битая'),
                                     ('битая', 'Битая')])
    steering_wheel = SelectField('Руль', validators=[DataRequired()],
                                 render_kw={
                                    "class": "form-control form-control-sm"},
                                 choices=[('левый', 'Левый'),
                                          ('правый', 'Правый')])
    wheeldrive = SelectField('Привод', validators=[DataRequired()],
                             render_kw={"class": "form-control form-control-sm"},
                             choices=[('передний', 'Передний'),
                                      ('задний', 'Задний'),
                                      ('полный', 'Полный')])
    color = StringField('Цвет', validators=[DataRequired()],
                        render_kw={"class": "form-control form-control-sm"})

    model = SelectField('Модель', validators=[DataRequired()],
                        render_kw={"class": "form-control form-control-sm"},
                        choices=[])
    mileage = IntegerField('Пробег', validators=[DataRequired()],
                           render_kw={"class": "form-control form-control-sm",
                                      "placeholder": "Введите пробег"})
    brand = SelectField('Марка', validators=[DataRequired()],
                        render_kw={"class": "form-control form-control-sm"},
                        choices=[])
    year = IntegerField('Год выпуска', validators=[DataRequired()],
                        render_kw={"class": "form-control form-control-sm",
                                   "placeholder": ""})
    body_type = SelectField(
        'Тип кузова', validators=[DataRequired()],
        render_kw={"class": "form-control form-control-sm",
                   "placeholder": ""},
        choices=[('седан', 'Седан'), ('универсал', 'Универсал'),
                 ('купе', 'Купе'), ('пикап', 'Пикап'), ('лимузин', 'Лимузин')])
    type_engine = SelectField('Тип двигателя', validators=[DataRequired()],
                              render_kw={"class": "form-control form-control-sm",
                                         "placeholder": ""},
                              choices=[('бензин', 'Бензин'),
                                       ('дизель', 'Дизель')])
    gear = SelectField('Коробка передач', validators=[DataRequired()],
                       render_kw={"class": "form-control form-control-sm",
                                  "placeholder": ""},
                       choices=[('механика', 'Механика'),
                                ('автомат', 'Автомат')])
    url_picture = FileField('Изображение',
                            render_kw={
                                "type": "file", "class": "form-control-file",
                                "id": "exampleFormControlFile1",
                                "multiple": ""})
    submit = SubmitField('Разместить', render_kw={"class": "btn btn-success"})


class DeleteForm(FlaskForm):
    choice_yes = SubmitField('Удалить',  render_kw={"class": "btn btn-danger"})


class EditForm(FlaskForm):
    description = TextAreaField('Описание', validators=[DataRequired()],
                                render_kw={
                                    "class": "form-control", "rows": "3",
                                    "placeholder": "Опишите "})
    mileage = IntegerField('Пробег', validators=[DataRequired()],
                           render_kw={"class": "form-control",
                                      "placeholder": "Введите пробег"})
    price = IntegerField('Цена', validators=[DataRequired()],
                         render_kw={"class": "form-control",
                                    "placeholder": "100000"})
    url_picture = FileField('Изображения',
                            render_kw={
                                "type": "file", "class": "form-control-file",
                                "id": "exampleFormControlFile1",
                                "multiple": ""})

    submit = SubmitField('Сохранить', render_kw={"class": "btn btn-success"})


class FilterForm(FlaskForm):
    price_1 = IntegerField('Цена от', validators=[InputRequired()],
                           render_kw={"class": "form-control form-control-sm",
                                      "placeholder": "10000",
                                      "value": 0})
    price_2 = IntegerField('Цена до', validators=[InputRequired()],
                           render_kw={"class": "form-control form-control-sm",
                                      "placeholder": "200000",
                                      "value": 5000000})

    submit = SubmitField('Искать', render_kw={"class": "btn btn-success"})

webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required
from webapp.user.forms import RegistrationForm, LogoutForm
from webapp.market.models import Auto
from webapp.user.models import User

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Панель управления'
    form = RegistrationForm()
    logoutform = LogoutForm()
    auto_list = Auto.query.all()
    auto_active = Auto.query.filter_by(active=True).all()
    auto_all = len(auto_list)
    auto_true = len(auto_active)
    auto_false = auto_all - auto_true
    user_list = User.query.order_by(User.id).all()
    return render_template("admin/index.html", page_title=title,
                           form=form,
                           logoutform=logoutform,
                           auto_all=auto_all,
                           auto_true=auto_true,
                           auto_false=auto_false,
                           user_list=user_list)

webapp/images/views.py
from flask import Blueprint, send_from_directory, current_app


blueprint = Blueprint('img', __name__)

# Какой URL он подкладывает. hekp
@blueprint.route('/hekp/<path:filename>')
def send_file(filename):
    return send_from_directory(f'{current_app.static_folder}/static', filename)
# Куда он смотрит на самом деле
@blueprint.route('/hekp/uploaded/<path:filename>')
def send_picture(filename):
    return send_from_directory(
        f'{current_app.static_folder}/uploaded', filename)

@blueprint.route('/hekp/numbers/<path:filename>')
def send_number(filename):
    return send_from_directory(
        f'{current_app.static_folder}/numbers', filename)

webapp/market/views.py
import os

from flask import Blueprint, render_template, redirect, url_for, \
    request, current_app, flash, jsonify
from flask_login import current_user, login_required

from webapp.market.models import Auto, Params, Images, Auto_brand,\
    Auto_models
from webapp.user.forms import RegistrationForm, LogoutForm,\
    LoginForm
from webapp.market.forms import AddForm, DeleteForm, EditForm, FilterForm
from webapp.message.forms import MessageForm
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('market', __name__)


@blueprint.route('/')
def index():
    page_title = 'Не бита, не крашена!'
    fform = FilterForm()
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.order_by(Auto_brand.id).all()
    count = {}
    for br in brands:
        auto = Auto.query.filter_by(brand_id=br.id).all()
        count[br.name] = len(auto)
    page = request.args.get('page', 1, type=int)
    full_auto_list = Auto.query.order_by(Auto.id).all()
    auto_list = Auto.query.order_by(Auto.id).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    return render_template('market/index.html', page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, full_auto_list=full_auto_list,
                           count=count, fform=fform
                           )


@blueprint.route('/brand_<brand>')
def filter_brand(brand):
    page_title = 'Не бита, не крашена!'
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.filter_by(id=brand).all()
    page = request.args.get('page', 1, type=int)
    auto_list = Auto.query.filter_by(brand_id=brand).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    models = Auto_models.query.filter_by(brand_id=brand).all()
    count = {}
    for model in models:
        auto = Auto.query.filter_by(model_id=model.id).all()
        count[model.name] = len(auto)
    return render_template('market/filter_by_brand.html',
                           page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, models=models, count=count
                           )

@blueprint.route('/brand_<brand>/<model>')
def filter_model(brand, model):
    page_title = 'Не бита, не крашена!'
    form = LoginForm()
    logoutform = LogoutForm()
    brands = Auto_brand.query.filter_by(id=brand).all()
    page = request.args.get('page', 1, type=int)
    auto_list = Auto.query.filter_by(model_id=model).paginate(
        page, current_app.config['AUTO_PER_PAGE'], False)
    next_url = url_for('market.index', page=auto_list.next_num) \
        if auto_list.has_next else None
    prev_url = url_for('market.index', page=auto_list.prev_num) \
        if auto_list.has_prev else None
    models = Auto_models.query.filter_by(brand_id=brand).all()
    count = {}
    for model in models:
        auto = Auto.query.filter_by(model_id=model.id).all()
        count[model.name] = len(auto)
    return render_template('market/filter_by_brand.html',
                           page_title=page_title,
                           form=form,
                           logoutform=logoutform,
                           auto_list=auto_list.items,
                           next_url=next_url, prev_url=prev_url,
                           brands=brands, models=models, count=count
                           )


@blueprint.route('/registration')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    page_title = 'Регистрация на сайте - Не бита, не крашена!'
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()

    return render_template('user/registration.html', page_title=page_title,
                           form=form, regform=regform,
                           logoutform=logoutform)


@blueprint.route('/auto/add_auto')
@login_required
def add_auto():
    page_title = 'Разместить объявление на сайте - Не бита, не крашена!'
    form = LoginForm()
    regform = RegistrationForm()
    addform = AddForm()
    logoutform = LogoutForm()
    addform.brand.choices = [(
        brand.id, brand.name) for brand in Auto_brand.query.all()]

    addform.model.choices = [(
        model.id, model.name) for model in Auto_models.query.filter_by(
            brand_id=addform.brand.choices[0][0]).all()]

    return render_template('market/add.html', page_title=page_title,
                           form=form, regform=regform,
                           logoutform=logoutform, addform=addform)


@blueprint.route('/delete/auto_<id>', methods=['POST'])
def del_auto(id):
    auto = Auto.query.filter_by(id=id).first()
    auto.active = False
    db.session.commit()

    flash(f"Объявление {auto.name} успешно удалено!")
    return redirect(url_for('user.user_account', id=current_user.id))


@blueprint.route('/sell_auto/edit/<id>', methods=["GET", "POST"])
def edit_auto(id):
    page_title = 'Редактирование объявления'
    editform = EditForm()
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    auto = Auto.query.filter_by(id=id).first()
    if editform.validate_on_submit():
        auto.price = editform.price.data
        auto.description = editform.description.data
        auto.mileage = editform.mileage.data
        uploaded_files = request.files.getlist('url_picture')
        for file in uploaded_files:
            file.save(os.path.join(
                f'{current_app.static_folder}/uploaded', file.filename))
            new_auto_i = Images(
                auto_id=auto.id,
                url_picture=file.filename)
            db.session.add(new_auto_i)
        db.session.commit()
        flash(f"Объявление {auto.name} успешно отредактировано!")
        return redirect(url_for('market.auto_account', id=id))
    return render_template('market/edit.html', page_title=page_title,
                           logoutform=logoutform, editform=editform,
                           form=form, regform=regform, auto=auto)


@blueprint.route('/auto/<id>')
def brand(id):
    brands = Auto_brand.query.filter_by(id=id).all()
    brandArr = []
    modelArr = []
    for brand in brands:
        brandObj = {}
        brandObj['id'] = id
        brandObj['name'] = brand.name
        models = Auto_models.query.filter_by(brand_id=id).all()
        for model in models:
            modelObj = {}
            modelObj['id'] = model.id
            modelObj['name'] = model.name
            modelArr.append(modelObj)
            brandObj['models'] = modelArr
            brandArr.append(brandObj)
    return jsonify(brandObj)


@blueprint.route('/process_add', methods=['POST'])
@login_required
def process_add():
    addform = AddForm()
    brand = Auto_brand.query.filter_by(id=addform.brand.data).first()
    model = Auto_models.query.filter_by(id=addform.model.data).first()
    new_auto = Auto(
        price=addform.price.data,
        description=addform.description.data,
        name=f'{brand.name} {model.name}, {addform.year.data}',
        user_id=current_user.id,
        brand_id=brand.id,
        model_id=model.id
        )

    db.session.add(new_auto)
    db.session.commit()
    new_auto_p = Params(
        auto_id=new_auto.id,
        holders=addform.holders.data,
        condition=addform.condition.data,
        steering_wheel=addform.steering_wheel.data,
        wheeldrive=addform.wheeldrive.data,
        color=addform.color.data,
        model=model.name,
        mileage=addform.mileage.data,
        brand=brand.name,
        year=addform.year.data,
        body_type=addform.body_type.data,
        type_engine=addform.type_engine.data,
        gear=addform.gear.data)

    uploaded_files = request.files.getlist('url_picture')
    for file in uploaded_files:
        file.save(os.path.join(
            f'{current_app.static_folder}/uploaded', file.filename))
        new_auto_i = Images(
            auto_id=new_auto.id,
            url_picture=file.filename
        )
        db.session.add(new_auto_i)
    db.session.commit()
    db.session.add(new_auto_p)
    db.session.commit()
    flash(f"Объявление {new_auto.name} успешно размещено!")
    return redirect(url_for('market.index'))


@blueprint.route('/sell_auto/<id>')
def auto_account(id):
    auto = Auto.query.filter_by(id=id).first()
    form = LoginForm()
    regform = RegistrationForm()
    logoutform = LogoutForm()
    delform = DeleteForm()
    msgform = MessageForm()
    if auto.active is True:
        params = Params.query.join(Auto).filter_by(id=id).first()
        all_params = {
            'Владельцев по ПТС': params.holders,
            'Поколение': params.generation,
            'Состояние': params.condition, 'Руль': params.steering_wheel,
            'Привод': params.wheeldrive,
            'Цвет': params.color, 'Объём двигателя': params.engine_capacity,
            'Модель': params.model,
            'Пробег': params.mileage, 'Марка': params.brand,
            'Год выпуска': params.year,
            'Тип кузова': params.body_type,
            'Тип двигателя': params.type_engine,

webapp/templates/market/auto.html
{% extends 'base.html' %}

{% block auto_content %}
<div class="modal fade" id="DelModal" tabindex="-1" role="form" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="DelModal">Удалить объявление?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action='{{  url_for("market.del_auto", id=auto.id ) }}' method='POST'>
          <div class="modal-body">
            Вы действительно хотите снять обьявление с продажи?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            
            {{ delform.choice_yes() }}
          </div>
        </form>
      </div>
    </div>
  </div> 
        <div class="col-1" style="background:rgb(229, 241, 241)"></div>
        <div class="col-7">
            <h3>{{ auto.name }}</h3>
            {% if auto.user_id == current_user.id %}
            <button type="button" class="btn btn-link"><a href='{{ url_for("market.edit_auto", id=auto.id) }}'>Редактировать</a></button>
            {% endif %}
        {% if current_user.is_admin == current_user.id or auto.user_id == current_user.id %}
            <button type="button" class="btn btn-link" data-toggle="modal" data-target="#DelModal">Удалить</button>
        {% endif %}
            <div class="box" style="max-height: 600px; max-width: 600px">
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner" style="max-width: 800px; max-height: 600px">
                        <div class="carousel-item active">
                            <img src='{{ url_for("img.send_picture", filename=auto.images[0].url_picture ) }}' class="d-block w-100" alt="{{ img }}">
                        </div>
                            {% for img in auto.images[1:] %}
                            
                                <div class="carousel-item">
                                    <img src='{{ url_for("img.send_picture", filename=img.url_picture ) }}' class="d-block w-100" alt="...">
                                </div>
                            {% endfor %}
                        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div> 
            </div>
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist" style="padding-top:10px">
                    <a class="nav-item nav-link active" id="nav-description-tab" data-toggle="tab" href="#nav-description" role="tab" aria-controls="nav-description" aria-selected="true" >Описание</a>
                    <a class="nav-item nav-link" id="nav-params-tab" data-toggle="tab" href="#nav-params" role="tab" aria-controls="nav-params" aria-selected="false">Характеристики</a>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent" >
                <div class="tab-pane fade show active" id="nav-description" role="tabpanel" aria-labelledby="nav-description-tab">
                    <div class="row" style="margin: 15px">
                        {{ auto.description }}
                    </div>
                </div>
                <div class="tab-pane fade" id="nav-params" role="tabpanel" aria-labelledby="nav-params-tab" >
                    <div class="row" style="margin: 15px">
                        {% include 'market/params.html' %}
                    </div>
                    <div class="row">
                        <div class="col-9"></div>
                        <div class="col-3">#{{ auto.id }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4" style="background:rgb(245, 245, 245); height: 400px">
            <div class="row"><h4> {{ auto.price }} Р  </h4></div>
            <div class="box" >
                <div class="row" >
                    <div class="box" >
                    {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('user.user_account', id=user.id) }}">
                            {{ user.avatar }}
                        <p><h6>{{ user.name }}</h6></p>
                        </a>
                        <p> {{ user.number }}</p>
                        {% if user.id != current_user.id %}
                            <p>
                                <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#MessageModal">
                                    Написать сообщение
                                </button>
                            </p>
                        {% else %}
                            <a class="nav-link" href="{{ url_for('user.user_account', id=user.id) }}">Мой аккаунт</a>
                        {% endif %}
                    {% else %}
                        {{ user.avatar }}
                        <p><h6>{{ user.name }}</h6></p>
                       
                            <p>
                                Для того чтобы увидеть номер <br>или написать продавцу Вам <br> нужно
                                <button type="button" class="btn btn-outline-dark btn-sm" style="color:rgb(150, 140, 140)" data-toggle="modal" data-target="#LoginModal">войти</button>
                                или
                                <a href= "/registration"><button type="button" class="btn btn-outline-dark btn-sm" style="color:rgb(150, 140, 140)" >зарегистрироваться</button></a>
                            </p>
                        
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% include 'message/modal.html' %}
</div>
{% endblock auto_content %}

webapp/templates/market/deleted.html
{% extends 'base.html' %}

{% block content %}
<main style="min-height: 150px">
    <div class="container" style="padding-bottom: 35px;">
        <h2>Упс..</h2><br>
        <h4>
            Объявление снято с продажи или удалено.
        </h4>
    </div>
    <div class="row">
        <div class="col-2">
            <a class="nav-link text-muted" href="/">На главную</a>
        </div>
        {% if current_user.is_authenticated or current_user.is_admin %}
        <div class="col-2">
            <a class="nav-link text-muted" href="{{ url_for('user.user_account', id=current_user.id) }}">Аккаунт</a>
        </div>
        {% endif %}
        {% if current_user.is_admin %}
        <div class="col-3">
            <a class="nav-link text-muted" href="{{ url_for('admin.admin_index') }}">Панель управления</a>
        </div>
        {% endif %}
    </div>
</main>
{% endblock %}

webapp/templates/market/filter_by_brand.html
{% extends 'base.html' %}

{% block content %}
{% for brand in brands %}


   <h5> Все что нашли по вашему запросу:                            
    <a href="{{ url_for('market.filter_brand', brand=brand.id ) }}">
        <i>    {{ brand.name }}</i><br/>
    </a>    
    </h5>
<div class="row">
   <span class="border-bottom">
{% for model in models %}
    {% if count[model.name] == 0 %}
    
        {{ model.name }}
    
    <span class="badge" style="color: rgb(165, 165, 165)"><i>( {{ count[model.name] }}   )</i></span> 

    {% else %}
        <a href="{{ url_for('market.filter_model', brand=brand.id, model=model.id ) }}" >
            {{ model.name }}
        </a>
        <span class="badge" style="color: rgb(165, 165, 165)"><i>( {{ count[model.name] }}   )</i></span>
    {% endif %}
    {% endfor %}
    {% endfor %}
</span> 
</div>

{% if auto_list == [] %}
<p>
    <h4>По интересующей Вас модели нет ни одного объявления..</h4>
</p>
    
{% else %}
{% for auto in auto_list %}  
    {% if auto.active !=False %}
        <div class="row" >
            <div class="media" style="margin-bottom:15px; margin-top: 10px">
                <div class="col" style="min-width: 300px; ">
                    <a href="{{ url_for('market.auto_account', id=auto.id) }}">
                        <img class="rounded" style="width: 70%;" src='{{ url_for("img.send_picture", filename=auto.images[0].url_picture) }}'  alt="{{ auto.name }}"></a>
                    </a>
                </div>
                <div class="col-9">
                    <div class="row">
                        <div class="col-6" style="min-width:300px">
                            <div class="media-body">
                                <a href="{{ url_for('market.auto_account', id=auto.id) }}"><h5 class="mt-0">{{ auto.name }}</h5></a>
                            </div>
                        </div>
                        <div class="col-4">
                            <span class="badge badge-pill badge-light">
                                <h5>Цена: {{ auto.price }} </h5>
                                
                            </span><br/>
                            <div class="btn-group dropleft" >
                                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Подробнее
                                </button>
                                <div class="dropdown-menu" style="width: 400px; padding: 10px">
                                    {% if auto.description != None %}
                                        {{ auto.description[:100] }}...
                                        <a href="{{ url_for('market.auto_account', id=auto.id) }}">Смотреть</a>
                                    {% else %}
                                        <a href="{{ url_for('market.auto_account', id=auto.id) }}">Смотреть</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}   
{% endfor %}
{% endif %}

{% endblock content %} 

webapp/templates/market/flash.html
<div style="text-align:center">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
</div>

webapp/templates/market/header.html
<div class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/"><img width ='130' height='60' src="{{ url_for('img.send_file', filename = 'logo.png') }}" alt='лого' class="rounded-pill" style="margin-top:5px"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="/">Главная</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('user.user_account', id=current_user.id) }}">Аккаунт</a>
            </li>
            {% endif %}
            {% if current_user.is_admin %}
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Панель управления</a>
            </li>
            {% endif %}
            </ul>
            {% if not current_user.is_authenticated %}
            <div style="margin-top:5px">
                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#LoginModal">Войти</button>
                <a href= "/registration"><button type="button" class="btn btn-warning btn-sm">Регистрация</button></a>
            </div>
            {% endif %}
                {% if current_user.is_authenticated %}
                <a class="text-dark" href="{{ url_for('market.add_auto') }}">Разместить объявление</a>
                <button type="button" class="btn badge-dark" style="background-color:rgb(216, 179, 179)">
                        <a  class="text-muted" href="{{ url_for('user.user_account', id=current_user.id) }}" style="text-decoration:none;">{{ current_user.name }}</a>
                        <span class="badge badge-light"><a href="{{ url_for('message.messages') }}">Сообщения</a></span>
                </button>
                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#LogoutModal" style="margin-left:10px">Выход</button>
                {% endif %}
        </div>
    </nav>
</div>

webapp/templates/market/params.html
<ul>
    {% for t in all_params.items() %}
    {% if t[1] != None %}
        <li>{{ t[0] }}  :  {{ t[1] }}</li>
    {% endif %}
    {% endfor %}
</ul>